---
abstract: ~
author:
  - 'Joel Roth, <joelz@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
keywords:
  - audio
  - recording
  - mixing
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Audio-Nama
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 5.0
  Data::Section: 0
  Event: 0
  File::Copy: 0
  File::Copy::Link: 0
  File::Find::Rule: 0
  File::HomeDir: 0
  File::Slurp: 0
  File::Temp: 0
  Graph: 0
  IO::Select: 0
  IO::Socket: 0
  IPC::Open3: 0
  Modern::Perl: 0
  Module::Load::Conditional: 0
  Parse::RecDescent: 0
  Term::ReadLine::Gnu: 0
  Text::Format: 0
  Time::HiRes: 0
  YAML::Tiny: 0
  autodie: 0
  perl: 5.10.1
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/bolangi/nama
version: 1.073
